eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: client
spring:
  application: 
    name: client
env: 1111
girl:
  name: fa21123
  age: 31
