eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: client
spring:
  application: 
    name: client
env: t3st
girl:
  name: drfsdf123
  age: 33
