eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: client
spring:
  application: 
    name: client
env: test
girl:
  name: wangyangyang222
  age: 1344
