eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: client
spring:
  application: 
    name: client
env: abc
girl:
  name: lihongji222
  age: 13
