eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: clientname
spring:
  application: 
    name: client
env: dev
girl:
  name: lihongji1111
  age: 33
